services:
  mysql:
    image: mysql:8.1
    container_name: zgie_market_db
    restart: always
    command: --max_connections=1000 --default-authentication-plugin=mysql_native_password --innodb_lock_wait_timeout=500
    ports:
      - 3506:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=ssemarket
    volumes:
      - my-vol:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    environment:
      - TZ=Asia/Shanghai

  sse_market_server:
    image: sse_market_server:latest
    container_name: zgie_market_server
    restart: on-failure:3
    depends_on:
      - redis
      - mysql
    build: .
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    volumes:
      - /home/ubuntu/zgie-market/SSE_market_server/public:/app/public
      - /home/ubuntu/zgie-market/logs:/app/log
      - /home/ubuntu/zgie-market/database:/app/database

volumes:
  my-vol:

networks:
  sse_market_network:
    driver: bridge
